#!/usr/bin/env python
# -*- coding:utf-8 -*-
import rospy
from bridge_interfaces.srv import BridgeSrv, BridgeSrvResponse
from bridge_interfaces_ros1.srv import BridgeROS1Srv, BridgeROS1SrvResponse

class TestServerNode:
    def __init__(self):
        self.s = rospy.Service('bridge_srv', BridgeSrv, self.bridge_srv_callback)
        self.s_ros = rospy.Service('bridge_ros_srv', BridgeROS1Srv, self.bridge_srv_ros_callback)
    
    def bridge_srv_callback(self, request):
        success = True
        message = "The server received message like {} from client {}.".format(request.message, request.client_id)
        return BridgeSrvResponse(success, message)
    
    def bridge_srv_ros_callback(self, request):
        success = True
        message = "The server received message like {} from client {}.".format(request.message_ros1, request.client_id_ros1)
        return BridgeROS1SrvResponse(success, message)

def main():
    rospy.init_node('test_server_node', anonymous=True)
    print('Hi from test_server node.')
    try:
        TestServerNode()
        rospy.spin()
    except rospy.ROSInterruptException: pass

if __name__ == '__main__':
    main()
