#!/usr/bin/env python
# -*- coding:utf-8 -*-
import rospy
from bridge_interfaces.msg import Bridge, BridgeArray
from bridge_interfaces_ros1.msg import BridgeROS1, BridgeArrayROS1

class TestPubNode:
    def __init__(self):
        self.publisher = rospy.Publisher('bridge', BridgeArray, queue_size=10)
        self.publisher_ros = rospy.Publisher('bridge_ros', BridgeArrayROS1, queue_size=10)

    def pub_loop(self):
        while not rospy.is_shutdown():
            bridge_array_msg = BridgeArray()
            for i in range(5):
                bridge_msg = Bridge()
                bridge_msg.client_id = str(i)
                bridge_msg.message = "This is the test message No.{}".format(i)
                bridge_array_msg.bridge_array.append(bridge_msg)
            self.publisher.publish(bridge_array_msg)
            bridge_array_ros1_msg = BridgeArrayROS1()
            for i in range(5):
                bridge_ros1_msg = BridgeROS1()
                bridge_ros1_msg.client_id_ros1 = str(i)
                bridge_ros1_msg.message_ros1 = "This is the test message No.{}".format(i)
                bridge_array_ros1_msg.bridge_array_ros1.append(bridge_ros1_msg)
            self.publisher_ros.publish(bridge_array_ros1_msg)
            
            rospy.sleep(1.0)

def main():
    rospy.init_node('test_pub_node', anonymous=True)
    print('Hi from test_pub node.')
    try:
        node = TestPubNode()
        node.pub_loop()
    except rospy.ROSInterruptException: pass

if __name__ == '__main__':
    main()
